/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_angzangy_jni_GLVideoJni */

#ifndef _Included_com_angzangy_jni_GLVideoJni
#define _Included_com_angzangy_jni_GLVideoJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_init
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_surfaceCreated
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_surfaceChanged
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_surfaceDestroyed
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_render
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_setDataSource
  (JNIEnv *, jclass, jstring);


JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_prepare
  (JNIEnv *, jclass);


JNIEXPORT jint JNICALL Java_com_angzangy_jni_GLVideoJni_getVideoWidth
  (JNIEnv *, jclass);



JNIEXPORT jint JNICALL Java_com_angzangy_jni_GLVideoJni_getVideoHeight
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_start
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_pause
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_stop
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_angzangy_jni_GLVideoJni_release
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
