/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_angzangy_jni_VideoJni */

#ifndef _Included_com_angzangy_jni_VideoJni
#define _Included_com_angzangy_jni_VideoJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_init
  (JNIEnv *, jclass);
/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    setSurface
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_setSurface
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    surfaceDestroyed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_surfaceDestroyed
  (JNIEnv *, jclass);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_setDataSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    prepare
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_prepare
  (JNIEnv *, jclass);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    getVideoWidth
 */
JNIEXPORT jint JNICALL Java_com_angzangy_jni_VideoJni_getVideoWidth
  (JNIEnv *, jclass);


/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    getVideoHeight
 */
JNIEXPORT jint JNICALL Java_com_angzangy_jni_VideoJni_getVideoHeight
  (JNIEnv *, jclass);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_start
  (JNIEnv *, jclass);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_pause
  (JNIEnv *, jclass);

/*
 * Class:     com_angzangy_jni_VideoJni
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_stop
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_angzangy_jni_VideoJni_release
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
